name = "discord-bot"
compatibility_date = "2024-09-01"
main = "./src/index.ts"

compatibility_flags = [
    "nodejs_compat"
]

# kv_namespaces = [
#     { binding = "", id = "" },
# ]

# d1_databases = [
#     { binding = "", database_name = "", database_id = "" }
# ]
