name: Coverage
on:
  - pull_request
  - pull_request_target
jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        # TODO: remove on ts-lint@v8
        run: npm install --legacy-peer-deps

      - name: Run tsc
        run: npm run prestart

      - name: Run tests
        run: npm run test:coverage
